/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nci.encrypt.userdatabase;

//imports
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;

/*
 * GUI.java
 * 14th November 2021
 * Security Fundamentals and Development CA1 Part 2
 * @authors: Group F - Ruby Lennon (x19128355), Emanuela Dudau (x19180675)
 * Description - App GUI
 */

public class GUI extends javax.swing.JFrame {
    //declare variables
    String userChoice, username, password;

    //create scanner object
    Scanner scan = new Scanner(System.in);

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();//inistialise GUI components
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appTa = new javax.swing.JTextArea();
        applicationTp = new javax.swing.JTabbedPane();
        userLoginPnl = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        userDetailsPnl = new javax.swing.JPanel();
        usernameTwoLbl = new javax.swing.JLabel();
        passwordTwoLbl = new javax.swing.JLabel();
        passwordTwoTf = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        updateDetailsBtn = new javax.swing.JButton();
        ppsnLbl = new javax.swing.JLabel();
        printUsernameLbl = new javax.swing.JLabel();
        emailTf = new javax.swing.JTextField();
        printDetailsBtn = new javax.swing.JButton();
        ppsnTf = new javax.swing.JTextField();
        fileReaderWriterPnl = new javax.swing.JPanel();
        fileTextTf = new javax.swing.JTextField();
        filenameLbl = new javax.swing.JLabel();
        filenameTf = new javax.swing.JTextField();
        writeFileBtn = new javax.swing.JButton();
        readFileBtn = new javax.swing.JButton();
        txtExtensionLbl = new javax.swing.JLabel();
        fileCheckerPnl = new javax.swing.JPanel();
        fileOnePnl = new javax.swing.JPanel();
        filenameOneTf = new javax.swing.JTextField();
        filenameOneLbl = new javax.swing.JLabel();
        txtExtensionOneLbl = new javax.swing.JLabel();
        fileTwoPnl = new javax.swing.JPanel();
        filenameTwoLbl = new javax.swing.JLabel();
        filenameTwoTf = new javax.swing.JTextField();
        txtExtensionTwoLbl = new javax.swing.JLabel();
        compareFilesBtn = new javax.swing.JButton();
        exitApplicationBtn = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl.setText("Student Details Portal");

        appTa.setColumns(20);
        appTa.setRows(5);
        appTa.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));
        jScrollPane1.setViewportView(appTa);
        appTa.getAccessibleContext().setAccessibleDescription("");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        createUserBtn.setText("Create New User");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");

        usernameLbl.setText("Username:");

        passwordLbl.setText("Password:");

        usernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLoginPnlLayout = new javax.swing.GroupLayout(userLoginPnl);
        userLoginPnl.setLayout(userLoginPnlLayout);
        userLoginPnlLayout.setHorizontalGroup(
            userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginPnlLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameLbl)
                    .addComponent(passwordLbl)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addComponent(passwordTf))
                    .addGroup(userLoginPnlLayout.createSequentialGroup()
                        .addComponent(createUserBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        userLoginPnlLayout.setVerticalGroup(
            userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLoginPnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLbl)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(userLoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserBtn)
                    .addComponent(logoutBtn)
                    .addComponent(loginBtn))
                .addGap(26, 26, 26))
        );

        applicationTp.addTab("User Login", userLoginPnl);

        userDetailsPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usernameTwoLbl.setText("Username:");

        passwordTwoLbl.setText("Password:");

        emailLbl.setText("Email:");

        updateDetailsBtn.setText("Update Details");

        ppsnLbl.setText("PPSN Number:");

        printUsernameLbl.setText("When logged in username prints here");

        printDetailsBtn.setText("Print Details");

        ppsnTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppsnTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userDetailsPnlLayout = new javax.swing.GroupLayout(userDetailsPnl);
        userDetailsPnl.setLayout(userDetailsPnlLayout);
        userDetailsPnlLayout.setHorizontalGroup(
            userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPnlLayout.createSequentialGroup()
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailsPnlLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPnlLayout.createSequentialGroup()
                                .addComponent(emailLbl)
                                .addGap(18, 18, 18)
                                .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPnlLayout.createSequentialGroup()
                                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordTwoLbl)
                                    .addComponent(usernameTwoLbl))
                                .addGap(18, 18, 18)
                                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(printUsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTwoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPnlLayout.createSequentialGroup()
                                .addComponent(ppsnLbl)
                                .addGap(18, 18, 18)
                                .addComponent(ppsnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(userDetailsPnlLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(updateDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        userDetailsPnlLayout.setVerticalGroup(
            userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsPnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTwoLbl)
                    .addComponent(printUsernameLbl))
                .addGap(18, 18, 18)
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTwoLbl)
                    .addComponent(passwordTwoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppsnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppsnLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(userDetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateDetailsBtn)
                    .addComponent(printDetailsBtn))
                .addContainerGap())
        );

        applicationTp.addTab("User Details", userDetailsPnl);

        fileTextTf.setBorder(javax.swing.BorderFactory.createTitledBorder("File Text"));
        fileTextTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTextTfActionPerformed(evt);
            }
        });

        filenameLbl.setText("Filename:");

        filenameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameTfActionPerformed(evt);
            }
        });

        writeFileBtn.setText("Write To File");

        readFileBtn.setText("Read File");

        txtExtensionLbl.setText(".txt");

        javax.swing.GroupLayout fileReaderWriterPnlLayout = new javax.swing.GroupLayout(fileReaderWriterPnl);
        fileReaderWriterPnl.setLayout(fileReaderWriterPnlLayout);
        fileReaderWriterPnlLayout.setHorizontalGroup(
            fileReaderWriterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileReaderWriterPnlLayout.createSequentialGroup()
                .addGroup(fileReaderWriterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileReaderWriterPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filenameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filenameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExtensionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileReaderWriterPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(writeFileBtn)
                        .addGap(60, 60, 60)))
                .addComponent(readFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(fileReaderWriterPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileTextTf)
                .addContainerGap())
        );
        fileReaderWriterPnlLayout.setVerticalGroup(
            fileReaderWriterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileReaderWriterPnlLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(fileReaderWriterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filenameLbl)
                    .addComponent(txtExtensionLbl))
                .addGap(18, 18, 18)
                .addComponent(fileTextTf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fileReaderWriterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(writeFileBtn)
                    .addComponent(readFileBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        applicationTp.addTab("File Reader/Writer", fileReaderWriterPnl);

        fileOnePnl.setBorder(javax.swing.BorderFactory.createTitledBorder("File One"));

        filenameOneLbl.setText("Filename:");

        txtExtensionOneLbl.setText(".txt");

        javax.swing.GroupLayout fileOnePnlLayout = new javax.swing.GroupLayout(fileOnePnl);
        fileOnePnl.setLayout(fileOnePnlLayout);
        fileOnePnlLayout.setHorizontalGroup(
            fileOnePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOnePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filenameOneLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filenameOneTf, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExtensionOneLbl)
                .addContainerGap())
        );
        fileOnePnlLayout.setVerticalGroup(
            fileOnePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOnePnlLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(fileOnePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameOneLbl)
                    .addComponent(filenameOneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExtensionOneLbl))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        fileTwoPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("File Two"));

        filenameTwoLbl.setText("Filename:");

        filenameTwoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameTwoTfActionPerformed(evt);
            }
        });

        txtExtensionTwoLbl.setText(".txt");

        javax.swing.GroupLayout fileTwoPnlLayout = new javax.swing.GroupLayout(fileTwoPnl);
        fileTwoPnl.setLayout(fileTwoPnlLayout);
        fileTwoPnlLayout.setHorizontalGroup(
            fileTwoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileTwoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filenameTwoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filenameTwoTf, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExtensionTwoLbl)
                .addContainerGap())
        );
        fileTwoPnlLayout.setVerticalGroup(
            fileTwoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileTwoPnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(fileTwoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameTwoLbl)
                    .addComponent(filenameTwoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExtensionTwoLbl))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        compareFilesBtn.setText("Compare Files");
        compareFilesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareFilesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileCheckerPnlLayout = new javax.swing.GroupLayout(fileCheckerPnl);
        fileCheckerPnl.setLayout(fileCheckerPnlLayout);
        fileCheckerPnlLayout.setHorizontalGroup(
            fileCheckerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileCheckerPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileOnePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(fileTwoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(fileCheckerPnlLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(compareFilesBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fileCheckerPnlLayout.setVerticalGroup(
            fileCheckerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileCheckerPnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fileCheckerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileOnePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileTwoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(compareFilesBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        applicationTp.addTab("File Checker", fileCheckerPnl);

        exitApplicationBtn.setText("Exit");
        exitApplicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(applicationTp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(titleLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(exitApplicationBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(applicationTp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitApplicationBtn)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compareFilesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareFilesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compareFilesBtnActionPerformed

    private void fileTextTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTextTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTextTfActionPerformed

    private void filenameTwoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameTwoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameTwoTfActionPerformed

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTfActionPerformed

    private void filenameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameTfActionPerformed

    private void ppsnTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppsnTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppsnTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if(usernameTf.getText().equalsIgnoreCase("")||passwordTf.getText().equalsIgnoreCase("")){
            //if text is missing in the required text fields the user is alerted
            appTa.append("\n\nPlease enter all required login information (username + password).");
        }else{
            username = usernameTf.getText();//get username from text field
            password = passwordTf.getText();//get password from text field

            String encryptedPassword = HashPassword(password);

            appTa.append(CheckUser(username, encryptedPassword));
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        if(usernameTf.getText().equalsIgnoreCase("")||passwordTf.getText().equalsIgnoreCase("")){
            //if text is missing in the required text fields the user is alerted
            appTa.append("\n\nPlease enter all required user creation information (username + password).");
        }else{
            username = usernameTf.getText();//get username from text field
            password = passwordTf.getText();//get password from text field

            String encryptedPassword = HashPassword(password);//get hash value of password

            String createUserResponse = CreateUser(username, encryptedPassword);//store the create user response to string

            if(createUserResponse.toUpperCase().startsWith("DUPLICATE ENTRY")){//if the create user response starts with duplicate entry
                appTa.append("\n\nSorry, this username is unavailable.");//print this message
            }else if(createUserResponse.toUpperCase().startsWith("DATA TRUNCATION")){//if the create user response starts with data truncation
                appTa.append("\n\nInvalid username or password length.");//print this message
            }else{
                appTa.append("\n\n" + createUserResponse);//else print this response
            }
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void exitApplicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationBtnActionPerformed
        //exit the application
        System.exit(0);
    }//GEN-LAST:event_exitApplicationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    //method to encrypt password using Hash (SHA-1 MessageDigest Algorithm)
    public static String HashPassword(String password){
        MessageDigest sha = null;//Message digests are secure one-way hash functions that take arbitrary-sized data and output a fixed-length hash value
        try{
            sha = MessageDigest.getInstance("SHA-1");//SHA-1 MessagDigest Algorithm selected
        }catch(NoSuchAlgorithmException e){
            System.out.println("No such algorithm");
        }

        byte b[] = password.getBytes();//Get they byte value of password

        byte[] hash = sha.digest(b);//byte array used to store the digested password using SHA-1 algorithm

        String encryptedPassword = new String(hash, StandardCharsets.UTF_8);//converting the hash to a string and storing in encryptedPassword

        return encryptedPassword;//return encryptedPassword

    }

    //method to create a new user in the database
    private static String CreateUser(String username, String password){
        try{
            String returnStatement;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/userstore", "root", "RLNCIsqlPass123*");//connect to userstore schema/database on localhost
            String sql = "INSERT INTO users (user_name, password) VALUES (?, ?)";//SQL statement to create new user in users table
            PreparedStatement statement = con.prepareStatement(sql);//prepared statement is more secure than plain statement against SQL injection
            statement.setString(1, username);//set the first statement parameter (?) to the username value
            statement.setString(2, password);//set the second statement parameter (?) to the password value

            statement.executeUpdate();//execute the statement

            con.close();//close connection

            return returnStatement = "New user created";
        }catch(SQLException e){
            System.out.println("SQL Error: " + e.getMessage());
            String sqlError;
            sqlError = e.getMessage();
            return sqlError;
        }
    }

    //method to check if a user exists in the database
    private static String CheckUser(String username, String password){
        try{
            String returnStatement;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/userstore", "root", "RLNCIsqlPass123*");//connect to userstore schema/database on localhost
            String sql = "SELECT * FROM users where user_name = ? and password = ?";
            PreparedStatement statement = con.prepareStatement(sql);//prepared statement is more secure than plain statement against SQL injection
            statement.setString(1, username);//set the first statement parameter (?) to the username value
            statement.setString(2, password);//set the second statement parameter (?) to the password value

            ResultSet results = statement.executeQuery();//execute the statement

            if(results.next()){
                con.close();//close connection
                return returnStatement = "\n\nYou have successfully logged in.";
            }else{
                con.close();//close connection
                return returnStatement = "\n\nLogin failed.";
            }

        }catch(SQLException e){
            System.out.println("SQL Error: " + e.getMessage());
            String sqlError;
            sqlError = e.getMessage();
            return sqlError;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea appTa;
    private javax.swing.JTabbedPane applicationTp;
    private javax.swing.JButton compareFilesBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTf;
    private javax.swing.JButton exitApplicationBtn;
    private javax.swing.JPanel fileCheckerPnl;
    private javax.swing.JPanel fileOnePnl;
    private javax.swing.JPanel fileReaderWriterPnl;
    private javax.swing.JTextField fileTextTf;
    private javax.swing.JPanel fileTwoPnl;
    private javax.swing.JLabel filenameLbl;
    private javax.swing.JLabel filenameOneLbl;
    private javax.swing.JTextField filenameOneTf;
    private javax.swing.JTextField filenameTf;
    private javax.swing.JLabel filenameTwoLbl;
    private javax.swing.JTextField filenameTwoTf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JLabel passwordTwoLbl;
    private javax.swing.JTextField passwordTwoTf;
    private javax.swing.JLabel ppsnLbl;
    private javax.swing.JTextField ppsnTf;
    private javax.swing.JButton printDetailsBtn;
    private javax.swing.JLabel printUsernameLbl;
    private javax.swing.JButton readFileBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel txtExtensionLbl;
    private javax.swing.JLabel txtExtensionOneLbl;
    private javax.swing.JLabel txtExtensionTwoLbl;
    private javax.swing.JButton updateDetailsBtn;
    private javax.swing.JPanel userDetailsPnl;
    private javax.swing.JPanel userLoginPnl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTf;
    private javax.swing.JLabel usernameTwoLbl;
    private javax.swing.JButton writeFileBtn;
    // End of variables declaration//GEN-END:variables
}
